networks:
  app_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app_network

  web:
    build: ./app/
    deploy:
      replicas: 3  # Scale to 3 instances
    ports:
      - "8001-8003:8080"
    volumes:
      - ./app/logs/:/app/logs/
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/userdb
    restart: always
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userdb
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

